# Bu gorev, Ubuntu & Rocky Linux için Apache & Php kutuphane yüklemesinini gerçekleştirir.
      - name: İşletim sistemlerini tespit et.
        debug: var=ansible_os_family
        tags: web_sunuculari
      
      - name: Dosyalardan Değişkenleri oku.
        include_vars: "{{ lookup('first_found', params) }}"
        vars: 
          params:
            files:
              - "roles/vars/apache_{{ ansible_os_family }}.yml"
              - "roles/vars/apache_varsayilan.yml"
        tags: web_sunuculari

      - name: Bu gorev, Ubuntu Apache & Php Kutuphane yuklemsi ile birlikte packet index'ini günceller.
        ansible.builtin.package:
            name:
              - "{{ apache_sunucusu }}"
              - "{{ php_kutuphane }}"
            state: latest
        tags: web_sunuculari
      
      - name: Bu gorev, Rocky Linux Apache servisini çalıştırır.
        service:
          name: "{{ webservis }}"
          state: started
          enabled: yes
        when: ansible_distribution == "Rocky"
        tags: web_sunuculari

      - name: Bu gorev, Rocky Linux'un Http portunu açar.
        firewalld:
          port: 80/tcp
          permanent: yes
          state: enabled
        when: ansible_distribution == "Rocky"
        register: rockyfrwll
        tags: web_sunuculari
      
      - name: Bu gorev, Rocky Linux'ın Firewall servisini restart eder.
        systemd:
          name: firewalld
          state: reloaded
        when: ansible_distribution == "Rocky" and rockyfrwll.changed
        tags: web_sunuculari

      - name: Bu gorev, Web sunuculuarına, Config belgelerini kopyalama işlemini gerçekleştirir.
        copy:
          src: "{{ yerelconf }}"
          dest: "{{ hedefconf }}"
          owner: root
          group: root
          mode: 0644
        register: conf
        tags: web_sunuculari
      
      - name: Bu gorev, Web sunucularının Apache servislerini restart eder.
        service:
          name: "{{ webservis }}"
          state: restarted
        when: conf.changed
        tags: web_sunuculari

      - name: Bu gorev, Web sunuculuarına, varsayılan html sayfasını kopyalama işlemini gerçekleştirir.
        copy:
          src: "{{ projeklasor }}"
          dest: "{{ hedefklasor }}"
          owner: root
          group: root
          mode: 0644
        tags: web_sunuculari